name: Sync LeetCode Solutions

on:
  schedule:
    - cron: '0 8 * * 6'  # Runs every Saturday at 8 AM
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  sync_leetcode:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Sync LeetCode solutions
      - name: Sync LeetCode Solutions
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: 'leetcode_solutions'
          verbose: true
          commit-header: '[LeetCode Sync]'
